
version: "3"

services:

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "52181:52181"
    networks:
      - net_102
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=52181

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "59092:59092"
    networks:
      - net_102
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:52181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:59092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:59092
    depends_on:
      - zookeeper
      
networks:
  net_102:
    ipam:
      driver: default
      config:
        - subnet: "169.254.102.0/24"