
version: "3"

services:

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      # Config #1
      #- "2181:2181"

      # Config #2
      #- "52181:2181"

      # Config #3
      - "52181:52181"

    networks:
      - net_102
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      # Config #1
      #- "9092:9092"

      # Config #2
      #- "59092:9092"

      # Config #3
      - "59092:59092"

    networks:
      - net_102
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      
      # Config #1
      #- KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092

      # Config #2
      #- KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      #- KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:59092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://localhost:59092
      #- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

      # Config #3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:52181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:59092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:59092

    depends_on:
      - zookeeper
      
networks:
  net_102:
    ipam:
      driver: default
      config:
        - subnet: "169.254.102.0/24"